### ISSUE TITLE
Asynchronous shader DXVK 1.2.1 ?

### ISSUE THREAD

**Issue by massatt212** [jomihaka/dxvk-poe-hack#18]
are we going to get an update or this is the end of the project
or are their Asynchronous shader DXVK builds out their ?

**Comment by jomihaka** [comment]
What exactly is the problem?

**Comment by massatt212** [comment]
is their going to be a version 1.2.1 with async enable ?

**Comment by jomihaka** [comment]
I guess you mean can I upload a binary of dxvk 1.2.1 with the patch applied?

Sure, I'll do that at some point.

**Comment by massatt212** [comment]
please do no one seems to be doing it
and the demand for it is high

**Comment by jomihaka** [comment]
done

**Comment by massatt212** [comment]
Is it on always or needs a command?

**Comment by jomihaka** [comment]
As the README says, no it's not always on. You need to set environment variable DXVK_ASYNC=1.

**Comment by massatt212** [comment]
Thx you

**Comment by massatt212** [comment]
DXVK_ASYNC=1 %command%

will that command work in Proton cause i dont see any performance difference when i enter this

**Comment by goldpaw** [comment]
I'm using this to launch PoE in proton: 
DXVK_STATE_CACHE=0 DXVK_ASYNC=1 %command%

Still stutters here and there, but it does that on windows too. Those launch arguments are what has worked best for me. No others, none of those to preload, or increase the garbage collection or anything. They are counter productive to the async patches, I think(?).

**Comment by goldpaw** [comment]
Oh, and not sure about anybody else, but I disable engine multithreading in the PoE graphic options. There's multithreading built into DXVK, I think(?), and enabling the PoE one makes DXVK perform worse. At least my fps is far higher with PoE multithreading off.

**Comment by massatt212** [comment]
i think soulcalibur 6 is a problem game
it just stutters with async on or off

**Comment by massatt212** [comment]
can we get an update for 1.2.2 ?
