### ISSUE TITLE
Please clarify your instructions

### ISSUE THREAD

**Issue by danilo-bc** [jomihaka/dxvk-poe-hack#3]
First of all, thanks a lot for this short, but very effective hack.

I want to experiment this with other games, but I need clarification on

>  If trying it for other games, set dxvk.useAsyncPipeCompiler and dxvk.dontWaitForShaders to true in config

Is this done with meson? If so, how? If you provide a few command lines, it will be very helpful. If you can provide a quick snippet of how your release builds were built in your system, it would also be very helpful.

Thanks in advance.

EDIT: I reckon you're referring to your patch file, but you can specify that the user has to edit the patch file beforehand in those certain lines.

**Comment by jomihaka** [comment]
I added link for configuration instructions to README.
