### ISSUE TITLE
Rebase?

### ISSUE THREAD

**Issue by GloriousEggroll** [jomihaka/dxvk-poe-hack#5]
Hey, hate to bug ya but can we get a rebase of the patch with current git? dxvk_graphics.cpp is not compatible with the patch currently

**Comment by jomihaka** [comment]
Should be working again.

**Comment by GloriousEggroll** [comment]
he broke it again, lol, easy fix this time. Here's the fix:

```
@@ -763,6 +763,8 @@ namespace dxvk {
     void commitComputeInitBarriers();
     void commitComputePostBarriers();
     
+    bool checkAsyncCompilationCompat();
+    
   };
   
-}
\ No newline at end of file
+}
```

**Comment by jomihaka** [comment]
Unsurprisingly he keeps dropping breaking commits one by one, so I won't be updating the patch until he calms down.

**Comment by HeyItsBATMAN** [comment]
I tried my best to update your patch to version 0.81 of DXVK to get a hybrid between the new state cache while also allowing async compilation and a hybrid sure came out, a hybrid monster that is.  
Async compilation kinda works as well as state cache building, but the state cache somehow builds slower than when async compilation is disabled.
So far I only tested it with Overwatch, but when async is enabled an empty cache still builds up more smoothly than when using an empty cache without async.  
After 1 match with async disabled I had a state cache of about 3.6mb while with async enabled only about 0.8mb.

@jomihaka and @GloriousEggroll you are both smarter than me, so if you have the time, can you take a look at [the modified patch](https://github.com/HeyItsBATMAN/dxvk-async/blob/master/dxvk-async.patch)?

**Comment by jomihaka** [comment]
I updated the patch and it should be state cache compatible now. Please test that it isn't much worse than 0.72.
